package main.java.com.oli.routing;

enum RoadType {
    MOTORWAY, MOTORWAY_LINK, TRUNK, TRUNK_LINK, PRIMARY, PRIMARY_LINK, SECONDARY, TERTIARY, ROAD, RESIDENTIAL, LIVING_STREET, PEDESTRIAN, SERVICE, TRACK, CYCLEWAY, FOOTWAY, PATH, STEPS, WATERWAY, UNCLASSIFIED
}

